language: objective-c
osx_image: xcode7.3

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=UnboxedAlamofire.xcodeproj
  matrix:
    - SCHEME="UnboxedAlamofire_iOS"
    - SCHEME="UnboxedAlamofire_OSX"
    - SCHEME="UnboxedAlamofire_tvOS"    

before_install:
  - brew install xctool

script:   
  - xctool -workspace $XCODE_WORKSPACE -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xctool -workspace $XCODE_WORKSPACE -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
